### ISSUE TITLE
[Question] How to keep my foam template repo up to date with foam development?

### ISSUE THREAD

**Issue by kodonoboken** [foambubble/foam-template#11]
I'm currently using foam-gatsby-template version of foam. I've gotten feedback from Mathieu on how to keep my frontend up to date with gatsby-theme-garden but am unsure how for foam.

**Comment by riccardoferretti** [comment]
this is still to be defined, see the ongoing conversation here: https://github.com/foambubble/foam/issues/453

**Comment by riccardoferretti** [comment]
closing as all further conversations will take place at https://github.com/foambubble/foam/issues/453
