### ISSUE TITLE
[Question] when I click - [[inbox]]  in readme.md in github.it show 404 pages

### ISSUE THREAD

**Issue by qingyi-wang** [foambubble/foam-template#14]
when I click "- [[inbox]]"  at readme.md in github. it shows 404 pages. but, when I add a .md in tail addre, it could work. how can click show easily in github

**Comment by riccardoferretti** [comment]
I believe you mean the github web ui (as opposed to github pages).

The solution is to set `foam.edit.linkReferenceDefinitions` to `withExtensions`.
