### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by geekscrapy** [foambubble/foam-template#20]
There doesn't seem to be a quick/automated way to rename a file and have all the existing links be changed.

I presume you could do a global find and replace? How do people currently deal with renaming files?

**Comment by brentjanderson** [comment]
I name my files with essentially a timestamp (e.g. `202008110956.md`). The title of the document carries through to the references. 

I'm new to Zettelkasten, but this seems in line with the idea of [add identity](https://zettelkasten.de/posts/add-identity/) and how Niklas Luhmann organized his notes.

I have a `tasks.json` file in `.vscode`:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "newFile",
      "command": "touch `date +%Y%m%d%H%M`.md; code -r `date +%Y%m%d%H%M`.md",

      "type": "shell",
      "problemMatcher": [],
      "presentation": {
        "echo": false,
        "reveal": "silent",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": false,
        "clear": true
      },
      "promptOnClose": false
    }
  ]
}

```

I've also added a keybinding to my local user keybindings:

```json
  {
    "key": "shift+alt+n",
    "command": "workbench.action.tasks.runTask",
    "args": "newFile"
  }
```

So, when I hit `shift+alt+n`, it generates a new file with a timestamp for a name and drops me in.

**Comment by geekscrapy** [comment]
Apart from having a generic name, I don't see how this addresses the issue?

If I want a new note I'll just use the existing New Note command, and if I want a daily not I'll use the Daily Note command?

**Comment by riccardoferretti** [comment]
this needs to be managed by the extension, and the work is tracked in https://github.com/foambubble/foam/issues/305
