### ISSUE TITLE
Add an example template

### ISSUE THREAD

**Issue by alongwill** [foambubble/foam-template#29]
The introduction to note templates could be improved if one or more example templates were included to:

a) Demonstrate how to use VS code variables
b) Give an example of what a useful template could be. The following examples have been given:

- a template for book reviews
- a template for daily notes
- a template for meetings

Then this page could be improved: https://github.com/foambubble/foam-template/blob/master/docs/features/note-templates.md

Many Thanks 👍

**Comment by riccardoferretti** [comment]
hi @alongwill, thanks for reporting this, would you like to give it a shot? 
I am happy to support

**Comment by riccardoferretti** [comment]
also mentioned in https://github.com/foambubble/foam/issues/400

**Comment by riccardoferretti** [comment]
moving the conversation to https://github.com/foambubble/foam/issues/486
