### ISSUE TITLE
Getting Started Video

### ISSUE THREAD

**Issue by ajeetshergill** [foambubble/foam-template#5]
I cloned the repo but I still don't understand how to get started with it. The CTRL + ` or Ctrl+Shift+p.. like I don't get how to create stuff and things. Can someone make a quick video on how to use it? How to get the graphs.

**Comment by jevakallio** [comment]
@ajeetshergill, in fact @zacjones93 recorded an Egghead video, maybe this would be helpful:
https://egghead.io/lessons/vs-code-create-a-second-brain-in-vscode-with-foam
