### ISSUE TITLE
Unable to install 'foam.foam-vscode' extension because it is not compatible with the current version of VS Code (version 1.45.1).

### ISSUE THREAD

**Issue by jayjansheski** [foambubble/foam-template#8]
Hi! I'm getting this error message after forking the repository, cloning, and opening it in VS Code:

> Unable to install 'foam.foam-vscode' extension because it is not compatible with the current version of VS Code (version 1.45.1).

About VS Code:

> macOS 10.15.5
> Version: 1.45.1
> Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
> Date: 2020-05-14T08:33:47.663Z
> Electron: 7.2.4
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 19.5.0

Happy to provide more information if it's helpful.

**Comment by jevakallio** [comment]
@jayjansheski I wonder what about it makes it incompatible! I'll try to figure that out, it's probably just a technicality.

Meanwhile, I'm on VS Code 1.46 and that seems to work. Could you try to upgrade?

![image](https://user-images.githubusercontent.com/1203949/86411991-f5f81480-bcb5-11ea-8cba-88aedbfcf87e.png)

**Comment by jayjansheski** [comment]
Voila! Had to re-download VS Code for some reason to get the update. Thanks!
